package com.delma.aiservice.serviceImpl;
// ConsultationAiService
//
// The AI part of Phase 2.
// Takes raw doctor notes → calls Groq → returns patient-friendly report.
//
// What AI does here:
// 1. Expansion — "Unstable Angina" → 4-sentence plain English explanation
// 2. Translation — "Aspirin 75mg OD" → "Take 1 tablet every morning after food"
// 3. Safety info — standard drug warnings added to each medication
// 4. Structure — formats into 7 clear sections for patient
//
// What AI does NOT do:
// - Does not diagnose
// - Does not change medications
// - Does not add clinical information not in doctor's notes
// ─────────────────────────────────────────────────────────────────────────────

import com.delma.aiservice.agent.feign.AppointmentClient;
import com.delma.aiservice.kafka.ConsultationNotesEvent;
import com.delma.aiservice.service.ConsultationAiService;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.*;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.stream.IntStream;


@Slf4j
@Service
@RequiredArgsConstructor
public class ConsultationAiServiceImpl implements ConsultationAiService {

    private final RestTemplate restTemplate;
    private final ObjectMapper objectMapper;
    private final AppointmentClient appointmentNotesClient;

    @Value("${GROQ_API_KEY}")
    private String groqApiKey;

    @Value("${GROQ_API_URL}")
    private String groqApiUrl;

    @Override
    public void processNotes(ConsultationNotesEvent event){
        log.info("Expanding consultation notes for notesId: {}", event.getNotesId());

        // 1. Format medications into readable text form the prompt;
        String medsFormatted = formatMedications(event.getMedications());

        // 2. Build prompt with doctors's note;
        String prompt = buildPrompt(event,medsFormatted);

        // 3. call groq llm
        String aiReport = callGroq(prompt);

        // 4. Save Ai report back to app ms via Feign
        try{
            appointmentNotesClient.updateAiReport(event.getNotesId(), aiReport);
            log.info("AI report saved for notesId: {}", event.getNotesId());
        } catch (Exception e) {
            log.error("Failed to save AI report for notesId: {}. Error: {}",
                    event.getNotesId(), e.getMessage());
        }
    }
    private String callGroq(String prompt) {
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        headers.set("Authorization", "Bearer " + groqApiKey);

        Map<String, Object> body = new LinkedHashMap<>();
        body.put("model", "llama-3.1-8b-instant");
        body.put("messages", List.of(
                Map.of("role", "user", "content", prompt)
        ));
        body.put("max_tokens", 1500);
        body.put("temperature", 0.3);
        // Low temperature = consistent, structured output
        // Medical docs need consistency not creativity

        try {
            ResponseEntity<String> response = restTemplate.exchange(
                    groqApiUrl, HttpMethod.POST,
                    new HttpEntity<>(body, headers),
                    String.class
            );
            JsonNode root = objectMapper.readTree(response.getBody());
            String result = root.path("choices").get(0)
                    .path("message").path("content").asText();
            log.info("Groq generated consultation report successfully");
            return result;
        } catch (Exception e) {
            log.error("Groq call failed: {}", e.getMessage());
            // Fallback — patient still gets something useful
            return buildFallbackReport();
        }
    }


    private String buildFallbackReport() {
        return """
            CONSULTATION SUMMARY
            Your consultation notes have been saved successfully.
            Your doctor has recorded your visit details.
            
            IMPORTANT
            Please contact your doctor directly for a detailed summary
            of your consultation and prescription details.
            
            DISCLAIMER
            This report is generated by Delma Health Platform.
            Always follow your doctor's direct advice.
            In case of emergency, visit the nearest hospital immediately.
            """;
    }

    // Format medication list into numbered text for the LLM prompt
    private String formatMedications(
            List<ConsultationNotesEvent.MedicationRecord> meds) {
        if (meds == null || meds.isEmpty()) {
            return "No medications prescribed.";
        }
        return IntStream.range(0, meds.size())
                .mapToObj(i -> {
                    ConsultationNotesEvent.MedicationRecord m = meds.get(i);
                   // 1. Augmentin (Amoxicillin) | Dose: 625mg | Frequency: Thrice daily | Duration: 5 days |
                    // Route: Oral | Note: Take after food
                    return String.format(
                            "%d. %s%s | Dose: %s | Frequency: %s | Duration: %d days" +
                                    " | Route: %s%s",
                            i + 1,
                            m.getDrugName(),
                            m.getGenericName() != null && !m.getGenericName().isBlank()
                                    ? " (" + m.getGenericName() + ")" : "",
                            m.getDose() != null ? m.getDose() : "as directed",
                            m.getFrequency() != null ? m.getFrequency() : "as directed",
                            m.getDurationDays() != null ? m.getDurationDays() : 0,
                            m.getRoute() != null ? m.getRoute() : "Oral",
                            m.getNotes() != null && !m.getNotes().isBlank()
                                    ? " | Note: " + m.getNotes() : ""
                    );
                })
                .collect(Collectors.joining("\n"));
    }
    private String buildPrompt(ConsultationNotesEvent e, String medsFormatted) {
        return """
            You are a medical documentation assistant for Delma Health Platform.
            A doctor has completed a video consultation and provided brief notes.
            Expand these into a complete, patient-friendly consultation report.
            
            ── DOCTOR'S NOTES ──
            Chief Complaint : %s
            Diagnosis       : %s %s
            Vitals          : %s
            
            Medications Prescribed:
            %s
            
            Tests Ordered   : %s
            Instructions    : %s
            Follow-up       : %d days
            
            ── GENERATE THIS EXACT STRUCTURE ──
            
            1. CONSULTATION SUMMARY
               2-3 sentences. What happened at this visit in plain English.
            
            2. YOUR DIAGNOSIS
               Explain the diagnosis clearly to a non-medical person.
               What is it, why is it happening, why did the doctor make this call.
               Maximum 4-5 sentences. No medical jargon.
            
            3. YOUR MEDICATIONS
               For EACH medication listed above:
               - Name and what it does (purpose in simple terms)
               - Exactly how to take it (dose + timing + with or without food)
               - How long to take it
               - One important warning to watch for
               Format as numbered list matching the medications above.
            
            4. TESTS ORDERED
               For each test, explain what it is and why it was ordered.
               If no tests, write "No tests ordered at this visit."
            
            5. RECOVERY INSTRUCTIONS
               Expand the doctor's instructions into clear, specific, actionable steps.
               What to do, what to avoid, dietary changes if any.
            
            6. FOLLOW-UP PLAN
               When to return (%d days from today).
               What symptoms need IMMEDIATE emergency attention.
               List 3-4 warning signs to watch for.
            
            7. DISCLAIMER
               "This report is an AI-generated summary of your consultation with
               your doctor at Delma Health. Always follow your doctor's direct
               advice. This document is for reference only and does not replace
               a medical prescription. In case of emergency, contact your doctor
               or visit the nearest hospital immediately."
            
            ── RULES ──
            - Use simple, clear language. No medical jargon.
            - Do not add any information not present in the doctor's notes.
            - If a section has no data, write "Not recorded at this visit."
            - Be warm and reassuring — the patient may be anxious.
            - Keep each section concise — doctor's notes are the only source.
            """.formatted(
                nullSafe(e.getChiefComplaint()),
                nullSafe(e.getDiagnosis()),
                e.getDiagnosisCode() != null ? "(" + e.getDiagnosisCode() + ")" : "",
                nullSafe(e.getVitals()),
                medsFormatted,
                nullSafe(e.getLabTests()),
                nullSafe(e.getInstructions()),
                e.getFollowUpDays() != null ? e.getFollowUpDays() : 7,
                e.getFollowUpDays() != null ? e.getFollowUpDays() : 7
        );
    }
    private String nullSafe(String value) {
        return value != null ? value : "Not recorded";
    }
}
