






server:
  port: 8091

spring:
  application:
    name: documentservice
  kafka:
    bootstrap-servers:  ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    url: jdbc:postgresql://localhost:5432/delma_document_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: admin
      password: admin123

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

aws:
  s3:
    bucket:
      name:  ${AWS_S3_BUCKET_DOCUMENTS}
    access:
      key:  ${AWS_ACCESS_KEY}
    secret:
      key:  ${AWS_SECRET_KEY}
    region: ${AWS_S3_REGION:ap-south-1}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true    # register this service with Eureka on startup
    fetch-registry: true          # fetch the registry so this service can call others
  instance:
    prefer-ip-address: true       # use IP address instead of hostname

jwt:
  secret: ${JWT_SECRET}

